<div class="row">
	<?php foreach($this->getMenu('dashboard') as $panel) { ?>
	
		<div class="col-md-4">

			<div class="panel panel-default">
				<div class="panel-heading">
					<?=$panel['label']?>
				</div>
				<div class="panel-body">
					<ul>
						<?php foreach($panel['children'] as $item) { ?>
							<li>
								<a href="<?=$item['link']?>"><?=$item['label']?></a>
							</li>	
						<?php } ?>
					</ul>
				</div>
			</div>

		</div>
  
	<?php } ?>
</div>
