<div 
	class="modal fade "
	id="modal-create"
	tabindex="-1"
	role="dialog"
	aria-labelledby="myModalLabel"
	aria-hidden="true"
	>
	
	<div class="modal-dialog modal-lg"> 
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">
					Aggiungi
				</h4>
			</div>
			<div class="modal-body">
				<div id="modal-item">
				</div>	
			</div>
			<div class="modal-footer">
				<div class="pull-right">
					<button type="button" class="btn btn-default" data-dismiss="modal">Chiudi</button>
					<button onclick="$('#modal-item form').submit()" type="button" class="btn btn-default btn-primary">Salva & Seleziona</button>				
				</div>
			</div>
		</div>
	</div>
</div>
