<h1><?=_('Try a demo app')?></h1>
<ul>
	<li><a href="<?=__URL__?>/app/simple" target="_blank">Simple app</a> - minimalist application to manage generic items</li>
	<li><a href="<?=__URL__?>/app/crm" target="_blank">Crm app</a> - lightweight CRM applicaton</li>
	<li><a href="<?=__URL__?>/app/site" target="_blank">Website demo</a> - a framework-based website</li>
	<li><a href="<?=__URL__?>/app/blog" target="_blank">Blog demo</a> - a framework-base blog</li>
	<li><a href="<?=__URL__?>/app/admin" target="_blank">Admin panel</a> - an administrative panel to manage stored data</li>		
</ul>
