<?php if (!isset($gridHandler))  $gridHandler = 'gridTable'; ?>
<div id="<?php echo $gridHandler ?>-wrapper">				
	<table id="<?php echo $gridHandler; ?>" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
		<thead>
			<?php foreach($grid->getColumns() as $column) {?>			
				<th ><?=$column->getLabel();?></th>
			<?php } ?>			
		</thead>	
		<tfoot>
		</tfoot>
		<tbody>
		</tbody>
	</table>		
</div>

<script>
	var <?=$gridHandler?> = null;
	jQuery(document).ready(function() {
		// grid init
		<?=$gridHandler?> = jQuery('#<?=$gridHandler?>').dataTable({
			bFilter: true,
			bJQueryUI: true,
			sServerMethod: "POST",
		    bServerSide: true,
    		bProcessing: true,
			iDisplayLength: 25,
			sAjaxSource: '<?=$grid->getService();?>',
			aoColumns: <?=$grid->getColumnsDefinition();?>,
			aaSorting: <?=$grid->getDefaultSortOrder()?>,
			"oLanguage": {
				"sEmptyTable":     "Nessun dato presente nella tabella",
				"sInfo":           "Vista da _START_ a _END_ di _TOTAL_ elementi",
				"sInfoEmpty":      "Vista da 0 a 0 di 0 elementi",
				"sInfoFiltered":   "(filtrati da _MAX_ elementi totali)",
				"sInfoPostFix":    "",
				"sInfoThousands":  ",",
				"sLengthMenu":     "Visualizza _MENU_ elementi",
				"sLoadingRecords": "Caricamento...",
				"sProcessing":     "Elaborazione...",
				"sSearch":         "Cerca:",
				"sZeroRecords":    "La ricerca non ha portato alcun risultato.",
				"oPaginate": {
					"sFirst":      "Inizio",
					"sPrevious":   "Precedente",
					"sNext":       "Successivo",
					"sLast":       "Fine"
				},
				"oAria": {
					"sSortAscending":  ": attiva per ordinare la colonna in ordine crescente",
					"sSortDescending": ": attiva per ordinare la colonna in ordine decrescente"
				}
			},
			"fnPreDrawCallback": function( oSettings ) {
				
	$('.dataTables_filter input').addClass('form-control input-sm');
$('.dataTables_filter input').css('width', '200px');
$('.dataTables_length select').addClass('form-control input-sm');
$('.dataTables_length select').css('width', '75px');
				
			}
		});
		// grid sort		
		//jQuery('#grid_filter').hide();		
	});	
	jQuery(window).resize(function(){
		jQuery("#<?=$gridHandler?>").css('width', '100%');				
	});
	
	jQuery(document).ready(function(){
		jQuery("#<?=$gridHandler?>").css('width', '100%');				
	});
	
	jQuery("html>head").append('<style>#gridTable tbody tr{cursor:pointer;}</style>');				
		
	jQuery(document).on("click","#gridTable tbody tr",function(e){
		var po = gridTable.fnGetPosition(this); 
		var id = gridTable.fnGetData(po)[0];		
		<?=@$grid->ClientEvents['row.click']?>
    });
	
	
	// internationalization url: http://datatables.net/plug-ins/i18n 
</script>