<!DOCTYPE html>
<html>
<head>
<title><?=$this->_name_?></title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="<?=__THEME_URL__?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?=__THEME_URL__?>/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="<?=__THEME_URL__?>/css/bootstrap.dataTables.css">
<link rel="stylesheet" href="<?=__THEME_URL__?>/css/bootstrap.fix.css">
<link rel="stylesheet" href="<?=__URL__?>/public/css/jquery.uploadify.min.css">
<?=$this->render_hook('append-css')?>
<script>var __URL__="<?=__URL__?>";var __HOME__="<?=__HOME__?>";</script>
<script src="<?=__URL__?>/public/js/jquery.min.js"></script>
<script src="<?=__URL__?>/public/js/jquery-ui.min.js"></script>
<script src="<?=__URL__?>/public/js/jquery.dataTables.min.js"></script>
<script src="<?=__URL__?>/public/js/jquery.uploadify.min.js"></script>
<script src="<?=__THEME_URL__?>/js/bootstrap.min.js"></script>
<script src="<?=__THEME_URL__?>/js/bootstrap.dataTables.js"></script>
<script src="<?=__URL__?>/public/js/hook.js"></script>
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/i18n/jquery-ui-i18n.min.js?ver=4.1'></script>
<script src="http://cdn.common-js.eu/api/js/0.2.0/common-ui.js?compile"></script>
<script src="<?=__URL__?>/public/js/common-ui-uploadify.js"></script>
<script>$ui.uploadifySwf = '<?=__URL__?>/public/swf/uploadify.swf';</script>
<script src="<?=__URL__?>/public/js/common-ws.js"></script>
<script>$ui.setLocale('it');</script>
<script>$ws.base = "<?=__HOME__?>";</script>
<script src="<?=__URL__?>/public/js/dialog.js"></script>
<script src="<?=__URL__?>/public/js/common.js"></script>
<?=$this->render_hook('append-js')?>
</head> 
<body>
<div class="<?=$container_class?>">
