<nav 
	class="navbar navbar-default <?=$navbar_class?>" 
	role="navigation"
	>

	<button
		type="button" 
		class="navbar-toggle"
		data-toggle="collapse" 
		data-target=".navbar-collapse"
		>
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>

	<div class="navbar-header">			
		<a id="top-logo" class="navbar-brand" href="<?=__HOME__?>">
			<img src="<?=__LOGO__?>" alt="<?=$this->_name_?>" height="35" style=""/>				
			<?=$this->_name_?>
		</a>
	</div>

	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<?php foreach($this->getMenu('navbar') as $item) { ?>
				<?php if (!isset($item->children)) { ?>
					<li>
						<a href="<?=$item->link?>" id="<?=$item->id?>">
							<?=$item->label?>
						</a>
					</li>						
				<?php } else { ?>
					<li class="dropdown">
						<a 
							id="<?=$item->id?>"
							class="dropdown-toggle"
							data-toggle="dropdown" 
							href="#"
							>
							<?=$item->label?>
						</a>
						<ul class="dropdown-menu">
							<?php foreach($item->children as $submenuitem) { ?> 
								<?php if ($submenuitem!="divider") { ?>
									<li><a role="menuitem" tabindex="-1" href="<?=$submenuitem->link?>"><?=$submenuitem->label?></a></li>
								<?php } else { ?>
									<li role="presentation" class="divider"></li>
								<?php } ?>
							<?php } ?>
						</ul>
					</li>
				<?php } ?>
			<?php } ?>
		</ul>
		<?php $this->getHook('navbar') ?>
	</div>
</nav>
