<?php
/**
 *
 *
 */

//
$title = isset($this->title) ? $this->title : t('Detail');

//
$modifyUrl = isset($this->modifyUrl) ? $this->modifyUrl : __HOME__;

//
$closeUrl = isset($this->closeUrl) ? $this->closeUrl : __HOME__;

?>

<div class="navbar-wrapper">

	<nav 
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default navbar-secondary" 
		role="navigation"
		> 

		<div class="navbar-header">    
			<span class="navbar-brand nav-bar-title">
                <?=$title?>
            </span>
		</div> 

		<div class="navbar-content">	
			<div class="pull-right"> 
				<?=$this->getHook('theme-nav-detail-buttons')?>
				<a
					href="<?=$modifyUrl?>"
					class="navbar-btn btn btn-default btn-primary"
					>
					<span class="glyphicon glyphicon-edit"></span>
					<?=t('Edit')?>
				</a>
                <a
					href="<?=$closeUrl?>"
					class="navbar-btn btn btn-default"
					>
					<?=t('Close')?>
				</a>
			</div>	
		</div>   
	</nav>
</div>
