<?php
/**
 *
 *
 */

//
$title = isset($this->title) ? $this->title : t('Create');

//
$createUrl = isset($this->createUrl) 
           ? $this->createUrl
           : __HOME__.'/'.$this->getUrlToken(0).'/create';
?>
<div class="navbar-wrapper">

	<nav 	
		role="navigation" 
		class="navbar navbar-default navbar-secondary" 
		data-spy="affix" 
		data-offset-top="10" 
		>

		<div class="navbar-header">    
			<span class="navbar-brand nav-bar-title">
                <?=$title?>
            </span>
		</div>
		
		<div class="navbar-content collapse navbar-collapse">				
			<div class="pull-right">

				<?php $this->getHook('theme-nav-list-buttons') ?>

                <?php if ($this->ability->create) { ?>
                    <a
                        href="<?=$createUrl?>"
                        class="navbar-btn btn btn-default"
                        >
                        <span class="glyphicon glyphicon-plus"></span>
                        <?=t('Nuovo')?>
                    </a>
                <?php } ?>

			</div>
		</div>
	</nav> 
</div>	