<?php
/**
 *
 *
 */

//
$title = isset($this->title) ? $this->title : t('Create');

//
$cancelUrl = isset($this->cancelUrl) ? $this->cancelUrl : __HOME__;

?>

<div class="navbar-wrapper">

	<nav
		data-spy="affix"
		data-offset-top="10"
		class="navbar navbar-default navbar-secondary"
		role="navigation"
		>

		<div class="navbar-header">
			<span class="navbar-brand nav-bar-title" >
                <?=$title?>
            </span>
		</div>

		<div class="navbar-content collapse navbar-collapse">
			<div class="pull-right">

                <?=$this->getHook('theme-nav-modify-buttons')?>

                <button
					class="navbar-btn btn btn-default btn-success"
					type="button"
					onclick="javascript:submitForm();"
					>
					<span class="glyphicon glyphicon-ok-sign"></span>
					<?=t('Save')?>
				</button>

                <button
					type="button"
					class="navbar-btn btn btn-default"
					data-ui-confirm="<?=t('Vuoi uscire senza salvare?')?>|<?=$cancelUrl?>"
                    >
					<?=t('Cancel')?>
				</button>

			</div>
		</div>
	</nav>
</div>	