<div class="navbar-wrapper">

	<nav 
		data-spy="affix" 
		data-offset-top="10" 
		class="navbar navbar-default navbar-secondary" 
		role="navigation"
		> 

		<div class="navbar-header" >    
			<span class="navbar-brand nav-bar-title" ><?=@$this->title?></span>
		</div> 

		<div class="navbar-content collapse navbar-collapse">		
			<div class="pull-right">
				<button 
					type="button" 
					data-toggle="tooltip" 
					data-original-title="Torna alla scermata precedente" 
					class="navbar-btn btn btn-default" 
					onclick="javascript:history.go(-1);" 
					>
					<span class="glyphicon glyphicon-remove"></span>
					Indietro
				</button>
				<button 
					class="navbar-btn btn btn-default btn-primary" 
					type="button" 
					onclick="javascript:submitForm();" 
					data-toggle="tooltip" 
					data-original-title="Salva il dato corrente"
					>
					<span class="glyphicon glyphicon-floppy-disk"></span>
					Salva
				</button>
				<?php $this->getHook('nav-modify-button') ?>
			</div>
		</div>   
	</nav>
</div>	