<form action="<?=__HOME__?>/user/save/" method="POST" data-ui-validate="success:'<?=$data->modal?'testModalSave':''?>'" id="item">
	<input type="hidden" name="id" value="<?=$this->item->id?>" />
        
		<input type="hidden" name="role" value="admin" />
        		
		<div >
            <label>Username*</label>
            <input data-ui-testing="required min3" type="text" name="username" value="<?=$this->item->username?>">
            <div data-ui-message="error:username:required">
               Il campo "username" non pu&ograve; essere vuoto.
            </div>
            <div data-ui-message="error:username:min3">
               Il campo "username" deve contenere almeno 3 caratteri.
            </div>
        </div>
        <div>
            <label>Password*</label>
            <input data-ui-testing="required min3" type="text" name="password" value="<?=$this->item->password?>">
            <div data-ui-message="error:password:required">
                Il campo "password" non pu&ograve; essere vuoto.
            </div>
            <div data-ui-message="error:password:min3">
               Il campo "password" deve contenere almeno 3 caratteri.
            </div>
        </div>
       
        <span>* Campo Obbligatorio</span>
</form>