<div class="tab-pane" id="tab2">

	<div class="row">
	
		<div class="col-sm-2">
			<label>Name</label>				
			<input 
				type="text"
				class="form-control"					
				name="data_arrivo" 
				value="<?=$this->item->name?>"
				/>
		</div>
		
		<div class="col-sm-2">
			<label>Value</label>
			<input 
				type="text"
				class="form-control"
				name="num_ord_fornitore"
				value="<?=$data->item->value?>"
				/>
		</div>
		
	</div>	

	<div class="row">
	
		<div class="col-sm-2">
			<label>Other</label>				
			<input 
				type="text"
				class="form-control"					
				name="other" 
				value="<?=$this->item->other?>"
				/>
		</div>
		
		<div class="col-sm-2">
			<label>Rest</label>
			<input 
				type="text"
				class="form-control"
				name="rest"
				value="<?=$data->item->rest?>"
				/>
		</div>
		
	</div>	

</div>
