<div class="tab-pane active" id="tab1">

	<div class="row">	
		<div class="col-sm-3">
			<label>Date</label>				
			<input 
				type="text"
				name="date" 
				class="form-control"					
				value="<?=$this->quote->date?>"
				data-ui-datepicker
				/>
		</div>		
		<div class="col-sm-9">
			<label>Account</label>			
			<div class="input-group">
				<input 
					type="text"
					name="account"
					class="form-control"
					value="<?=$this->quote->account?>"
					/>
				<span class="input-group-btn">
					<button 
						class="btn btn-default"
						onclick="return false;" 
						data-dialog="
							modal:'#modal-search',
							title:'Cerca Materiale',
							source:'crm/account-search-dialog',
							target:'[name=account]',
							size:'lg'" 
						>
						<i class="glyphicon glyphicon-search"></i>
					</button>
				</span>
			</div>
		</div>		
	</div>	

	<div class="row">	
		<div class="col-sm-12">
			<table class="table table-striped table-condensed table-compact">
				<thead>					
					<tr>
						<th width="70%">Product</th>
						<th width="10%">Price</th>
						<th width="10%">Quantity</th>
						<th width="10%">Partial</th>
						<th width="1%">&nbsp;</th>
					</tr>	
				</thead>
				<tbody>
					<tr data-ui-grid-input-row="name:'dettaglio',deleteButton:'.delete-row'">						
						<td>
							<input 
								type="hidden" 
								name="id" 
								value=""
								/>
							<div class="input-group">
								<input 
									type="text"
									name="dettaglio" 
									value=""
									class="form-control"
									data-ui-testing="required"
									/>	
								<span class="input-group-btn">
									<input 
										type="hidden"
										name="materiale"
										value="" 
										data-ui-render="
											source:'articoli/render',
											target:['[name=\'dettaglio_ordine[1][descrizione]\']','[name=\'dettaglio[1][dettaglio]\'','[name=\'dettaglio_ordine[1][per_iva]\''],
											layout:['{descrizione}','{codice_articolo}','{codice_iva}']"                                          
										/>
									<button 
										class="btn btn-default"
										onclick="return false;" 
										data-dialog="
											modal:'#modal-search',
											title:'Cerca Materiale',
											source:'crm/',
											target:':prev',
											size:'lg'" 
										>
										<i class="glyphicon glyphicon-search"></i>
									</button>									
								</span>
							</div>
						</td>			
						<td>							
							<input 
								type="text"
								name="price" 
								value=""
								class="form-control"
								/>			                     
						</td>
						<td>
							<input 
								type="text"
								name="quantity" 
								value=""
								class="form-control"
								/>			                     
						</td>		
						<td>
							<input 
								type="text"
								name="partial" 
								value=""
								class="form-control"
								readonly="readonly"
								/>			                     
						</td>
						<td>
							<button 
								type="button"
								class="delete-row btn btn-default btn-danger btn-block"								
								>                                            
								<span class="glyphicon glyphicon-remove"></span>
							</button>	                     
						</td>
					</tr>	
				</tbody>	
			</table>				
		</div>		
	</div>	
</div>
